### ISSUE TITLE
djongo.sql2mongo.SQLDecodeError on runserver of fresh project

### ISSUE THREAD

**Issue by radzhome** [nesdis/djongo#156]
#### One line description of the issue

sql decode error (see stack trace)

#### Python script

python manage.py runserver

Running latest django and djongo on python 3.7.0
Running older version of mongo db, 'version': '3.2.12' , could this be the cause?

#### Traceback

Django version 2.0.7, using settings 'content_services.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 725, in __iter__
    yield from iter(self._query)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 159, in __iter__
    self._cursor = self._get_cursor()
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 258, in _get_cursor
    cur = self.db_ref[self.left_table].aggregate(pipeline)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/pymongo/collection.py", line 2397, in aggregate
    **kwargs)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/pymongo/collection.py", line 2304, in _aggregate
    client=self.__database.client)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Unrecognized pipeline stage name: '$addFields'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1007, in apply_converters
    for row in map(list, rows):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1462, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1462, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/cursor.py", line 59, in fetchmany
    ret.append(self.result.next())
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 719, in __next__
    return next(self._result_generator)
  File "/Users/rwojcik/.local/share/virtualenvs/content_services-QwWaFh_z/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 737, in __iter__
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = %(0)s ORDER BY "django_admin_log"."action_time" DESC LIMIT 10
Pymongo error: {'ok': 0.0, 'errmsg': "Unrecognized pipeline stage name: '$addFields'", 'code': 16436}
Version: 1.2.29
[10/Jul/2018 20:06:09] "GET /admin/ HTTP/1.1" 500 337719

**Comment by hellonts** [comment]
me to  Sometimes refresh frshdjongo.sql2mongo.SQLDecodeError: FAILED SQL Version: 1.2.30
pymongo==3.6.1
django==2.0.5
djongo==1.2.30

**Comment by abawchen** [comment]
@hellonts @radzhome 
I guess the problem may be the version of `sqlparse` -- sqlparse 0.2.4 works well, but sqlparse 0.3.0 not.

**Comment by hellonts** [comment]
Ok Thanks.


| |
Alen
|
|
邮箱：ylfhellonts@126.com
|

Signature is customized by Netease Mail Master

On 03/13/2019 10:07, abawchen wrote:

@hellonts@radzhome
I guess the problem may be the version of sqlparse -- sqlparse 0.2.4 works well, but sqlparse 0.3.0 not.

**Comment by rajat45mishra** [comment]
File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 763, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 805, in _create
    self.db.create_collection(table)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 373, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection payment_checkout already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 700, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 783, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "payment_checkout" ("id" int32 NOT NULL PRIMARY KEY AUTOINCREMENT, "check_out_date_time" date NULL)
Version: 1.2.30

**Comment by rajat45mishra** [comment]
please help me to solve this issue

**Comment by artemnesterenko** [comment]
@rajat45mishra I'm facing the same issue

**Comment by rajat45mishra** [comment]
You can't use mptt module with mongodb you have to write a database router for switching SQL and nosql database . You can find examples of database routers in Django documentation

**Comment by artemnesterenko** [comment]
> @artemnesterenko You can't use mptt module with mongodb you have to write a database router for switching SQL and nosql database . You can find examples of database routers in Django documentation

I'm already using routers:
```python
class BaseMongoRouter:
    mongo_models = None

    def db_for_read(self, model, **hints) -> Optional[str]:
        if self.is_mongo_model(model=model):
            return settings.MONGO_DB_ALIAS
        return None

    def db_for_write(self, model, **hints) -> Optional[str]:
        if self.is_mongo_model(model=model):
            return settings.MONGO_DB_ALIAS
        return None

    def allow_relation(self, obj1, obj2, **hints) -> Optional[bool]:
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints) -> Optional[bool]:
        """Deny all migrations for mongodb and mongo-related models."""
        is_mongo_db = db == settings.MONGO_DB_ALIAS
        is_mongo_model = self.is_mongo_model(app_label=app_label, model_name=model_name)
        if is_mongo_db and is_mongo_model:
            return getattr(settings, "TEST", False)
        if is_mongo_db or is_mongo_model:
            return False
        return None

    def is_mongo_model(self, *, model=None, app_label=None, model_name=None) -> bool:
        if not model and not app_label:
            raise ValueError("Provide either model or app_label")
        if model:
            return model in self.mongo_models
        label_model_set = {
            (m._meta.app_label, m._meta.model_name) for m in self.mongo_models
        }
        return (app_label, model_name) in label_model_set
```
I allow migrations for mongo models only during testing to not create all tables in tests manually

**Comment by artemnesterenko** [comment]
When I run tests with an empty test db, I get:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 806, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 869, in _create
    type_code = props[1]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    main()
  File "manage.py", line 13, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 554, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 72, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 743, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 826, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: CREATE TABLE "table_name" ()
Version: 1.2.32
```

**Comment by rajat45mishra** [comment]
artemnesterenko can you show me your models.py file

**Comment by rajat45mishra** [comment]
Or try version 1.2.31

**Comment by artemnesterenko** [comment]
> Or try version 1.2.31

```python
Creating test database for alias 'mongo'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 769, in parse
    return handler(self, statement)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 894, in _insert
    self._query.execute()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 433, in execute
    res = self.db_ref[self.left_table].insert_many(docs, ordered=False)
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 745, in insert_many
    raise TypeError("documents must be a non-empty list")
TypeError: documents must be a non-empty list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    main()
  File "manage.py", line 13, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 554, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/creation.py", line 72, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 246, in apply_migration
    self.record_migration(migration)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 261, in record_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 83, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1332, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/djongo/cursor.py", line 53, in execute
    params)
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 706, in __init__
    self.parse()
  File "/usr/local/lib/python3.7/site-packages/djongo/sql2mongo/query.py", line 789, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "django_migrations" ("app", "name", "applied") VALUES (%(0)s, %(1)s, %(2)s)
Version: 1.2.31
```

**Comment by rajat45mishra** [comment]
Document should not be empty

**Comment by artemnesterenko** [comment]
> Document should not be empty
Yeah, I see :)
```python
djongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "django_migrations" ("app", "name", "applied") VALUES (%(0)s, %(1)s, %(2)s)
```
But this happens during inserting into "django_migrations" table which is made by djongo and I don't have control over it.

**Comment by rajat45mishra** [comment]
I solved that issue with degrading version

**Comment by artemnesterenko** [comment]
@rajat45mishra It seems I need to do something besides downgrading. Thank you for your time!

**Comment by artemnesterenko** [comment]
@rajat45mishra I've found what's the problem https://github.com/nesdis/djongo/issues/274#issuecomment-496844652

**Comment by mrbrazzi** [comment]
> > Document should not be empty
> 
> Yeah, I see :)
> 
> ```python
> djongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "django_migrations" ("app", "name", "applied") VALUES (%(0)s, %(1)s, %(2)s)
> ```
> 
I got same error with version 1.2.33 in fresh installation
> But this happens during inserting into "django_migrations" table which is made by djongo and I don't have control over it.
I downgrade to version 1.2.31 and the execution of *python manage.py migrate* works fine

**Comment by kunci115** [comment]
i downgrade to 1.2.31 and sqlparse also 0.2.4 but still not works in docker

**Comment by Vichoko** [comment]
I get this error while saving a model concurrently with many threads. added a retry system and kinda works

**Comment by UmairLakhani** [comment]
same issues.....! downgrade to 1.2.31 and sqlparse 0.2.4.. but still same problem

**Comment by froiskallico** [comment]
Hi, I was facing the same problem here. I runned `pip install --upgrade sqlparse` and it not works, after it i run `pip install --upgrade djongo` and it works...

The weird detail is that yesterday everything was workin on my computer at company. Today I tried pulled the repo at my laptop at home and the runserver raises that exception ... The good news is that now everything is working...

**Comment by alejandrohdo** [comment]
I have updated it django `pip install --upgrade djongo`, and I have done the migrations `python manage.py migrate --fake-initial` and it has been fixed

**Comment by qasim683** [comment]
> Ok Thanks. | | Alen | | 邮箱：ylfhellonts@126.com | Signature is customized by Netease Mail Master On 03/13/2019 10:07, abawchen wrote: @hellonts@radzhome I guess the problem may be the version of sqlparse -- sqlparse 0.2.4 works well, but sqlparse 0.3.0 not. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

thanks bro working for me with sqlparse 0.2.4

**Comment by BurhanuddinAbbas** [comment]
> @hellonts @radzhome
> I guess the problem may be the version of `sqlparse` -- sqlparse 0.2.4 works well, but sqlparse 0.3.0 not.

thanks , downgrading sqlparse library from 0.3.1 to 0.2.4 fixed the issue

**Comment by BurhanuddinAbbas** [comment]
> same issues.....! downgraded to 1.2.31 and sqlparse 0.2.4.. but still same problem

make sure to downgrade django and djongo library as well. In my case i had to install 
pip install djongo==1.2.31
pip install Django==2.2.8
pip install sqlparse==0.2.4

**Comment by padmakarkasture** [comment]
same problem..if anyone solved this please reply

**Comment by felixjff** [comment]
Had the same issue on my project. Updated Djongo with "'pip install --upgrade djongo" and it works now.

**Comment by bitdom8** [comment]
> Had the same issue on my project. Updated Djongo with "'pip install --upgrade djongo" and it works now.

solved

**Comment by Vitaee** [comment]
Still same problem for me;

django === 3.0
djongo === 1.3.6
sqlparse==0.2.4

**Comment by Vitaee** [comment]
Hello guys I fixed my issue. My requirements.txt file look like this;


```
sqlparse===0.2.4

django

dnspython

djangorestframework

PyJWT

pymongo

djongo

django-rest-passwordreset

django-cors-headers

Pillow
```

**Comment by prashant-sengar** [comment]
> Hello guys I fixed my issue. My requirements.txt file look like this;
> 
> ```
> sqlparse===0.2.4
> 
> django
> 
> dnspython
> 
> djangorestframework
> 
> PyJWT
> 
> pymongo
> 
> djongo
> 
> django-rest-passwordreset
> 
> django-cors-headers
> 
> Pillow
> ```

So what version of django and djongo solved the issue?

**Comment by Vitaee** [comment]
> > Hello guys I fixed my issue. My requirements.txt file look like this;
> > ```
> > sqlparse===0.2.4
> > 
> > django
> > 
> > dnspython
> > 
> > djangorestframework
> > 
> > PyJWT
> > 
> > pymongo
> > 
> > djongo
> > 
> > django-rest-passwordreset
> > 
> > django-cors-headers
> > 
> > Pillow
> > ```
> 
> So what version of django and djongo solved the issue?

Latest version of django and djongo solved my issue. When you don't specify library version in requirements.txt file , "pip" automatically install latest version of libraries.

**Comment by dayojohn19** [comment]
2021 and still the same problem

**Comment by Vitaee** [comment]
Hello @dayojohn19, can you try to delete your installed libraries then re-install them. Also you can try to create new django project ) if its accepteble ) it should work.

**Comment by tvandraren** [comment]
I'm facing a similar problem with a fresh project in Python 3.8

requirements.txt:
```
asgiref==3.5.0
backports.zoneinfo==0.2.1
Django==4.0.3
djongo==1.3.6
dnspython==2.2.1
pymongo==3.12.1
python-snappy==0.6.1
pytz==2022.1
sqlparse==0.2.4
tzdata==2022.1
winkerberos==0.9.0
```

models and query
```python
class Lengua(models.Model):
    nombre = models.TextField()
    lang_code = models.TextField()


class Palabra(models.Model):
    lengua = models.ForeignKey(Lengua, on_delete=models.PROTECT)
    lema = models.TextField()
    esActiva = models.BooleanField()
    fecha = models.DateTimeField(default=timezone.now)
```

this query works:
```python
KH = Lengua.objects.get(lang_code="KHU")
palabras = Palabra.objects.filter(
    lengua=KH,
    esActiva__in=[True]
)
```

this query doesn't work:
```python
palabras = Palabra.objects.filter(lema="-en")
```
nor any other variation with `__in` or `__starswith`

trace
```python
C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\Scripts\python.exe C:/Users/tvand/Documents/repos/khunlyngramnerk/manage.py runserver
Performing system checks...

Watching for file changes with StatReloader
System check identified no issues (0 silenced).
May 06, 2022 - 15:36:29
Django version 4.0.3, using settings 'khunlyngramnerk.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /merge
Traceback (most recent call last):
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 784, in __init__
    self._query = self.parse()
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 876, in parse
    raise e
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 857, in parse
    return handler(self, statement)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 933, in _select
    return SelectQuery(self.db, self.connection_properties, sm, self._params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 116, in __init__
    super().__init__(*args)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\query.py", line 152, in parse
    self.where = WhereConverter(self, statement)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\converters.py", line 27, in __init__
    self.parse()
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\converters.py", line 119, in parse
    self.op = WhereOp(
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\operators.py", line 475, in __init__
    self._statement2ops()
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\operators.py", line 428, in _statement2ops
    op = self._token2op(tok, statement)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\sql2mongo\operators.py", line 413, in _token2op
    raise SQLDecodeError
djongo.exceptions.SQLDecodeError: 

	Keyword: None
	Sub SQL: None
	FAILED SQL: ('SELECT "gramnerk_palabra"."id", "gramnerk_palabra"."lengua_id", "gramnerk_palabra"."lema", "gramnerk_palabra"."esActiva", "gramnerk_palabra"."fecha" FROM "gramnerk_palabra" WHERE "gramnerk_palabra"."lema" LIKE %(0)s OFFSET 1',)
	Params: (('-%',),)
	Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\gramnerk\views.py", line 176, in get
    for dupe in palabras[1:]:
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\models\query.py", line 320, in __iter__
    self._fetch_all()
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tvand\Documents\repos\khunlyngramnerk\venv\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError
[06/May/2022 15:36:34] "GET /merge HTTP/1.1" 500 196549
C:\Users\tvand\Documents\repos\khunlyngramnerk\gramnerk\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified no issues (0 silenced).
May 06, 2022 - 15:36:45
Django version 4.0.3, using settings 'khunlyngramnerk.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

```

**Comment by SwapnilKotkar** [comment]
> 2021 and still the same problem

@dayojohn19  2022 and still th same problem

my modules versions are:

Django==2.2.8
djongo==1.2.31
pymongo==3.12.3
sqlparse==0.2.4

still I have issue --> djongo.sql2mongo.SQLDecodeError

Help me, Please !!!!!!!!!!!!

Thanks in Advance

**Comment by parshadpatel** [comment]
Hello guys I fixed my issue. My requirements.txt file look like this;

**Comment by parshadpatel** [comment]
Hello guys I fixed my issue. My requirements.txt file look like this;

Django>3.2,<4.0 # Use 3.2 as it is LTS. 3.2.12/13
pymongo==3.12.1
djongo==1.3.6

:))

**Comment by PrachotanReddy** [comment]
@parshadpatel what does your pipfile look like? Which version of sqlparse are you using? I tried the above and its still not working for me

**Comment by ajwad-shaikh** [comment]
https://github.com/doableware/djongo/issues/562

Check this once, if you have a filter condition on a Boolean Field, this might be causing an issue

**Comment by parshadpatel** [comment]
> 
sqlparse == 0.2.4
