### ISSUE TITLE
When using an ArrayModelField field in admin, how can i add multiple embedded models at once?

### ISSUE THREAD

**Issue by thestick613** [nesdis/djongo#210]
Currently, i can add only one new item at a time, although i can remove multiple by checking Delete.

<img width="706" alt="screen shot 2018-11-08 at 16 15 01" src="https://user-images.githubusercontent.com/1608525/48203997-8101f980-e371-11e8-96de-e47c1cd06479.png">

I click save, then add the next one etc.

<img width="660" alt="screen shot 2018-11-08 at 16 15 51" src="https://user-images.githubusercontent.com/1608525/48204060-9ecf5e80-e371-11e8-984f-44132456c2ae.png">

relevant code:

    class ContainerList(models.Model):
        _id = models.CharField(max_length=256)

        def __str__(self):
            return self._id

        class Meta:
            managed = False

    class Entry(models.Model):
        # [...] fields
        lists = models.ArrayModelField(model_container=ContainerList, model_form_class=ContainerListForm)
        # [...] fields

**Comment by arindammanidas** [comment]
I'm also looking forward to this. :)

**Comment by nesdis** [comment]
You can add multiple array entries like this:

![image](https://user-images.githubusercontent.com/17020932/59560590-11de3900-9015-11e9-8922-2e514a2e20ba.png)

Djongo comes included with batteries included: 'dynamic_formsets'. This is how you do it:
 settings.py
``
INSTALLED_APPS = [
    'main_test.apps.MainTestConfig',
    'djongo.dynamic_formsets.apps.DynamicFormsetsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
``

When you include dynamic formsets in your installed apps, then your django admin changes to what I show in the picture above. Then, every time you click on 'add another' you can add more and more array entries dynamically.

Hope this answers your question.

**Comment by aggarwalnisha** [comment]
Hey @nesdis I tried to do the same, but could not see any changes. Am I correct in assuming that I need to add only `'djongo.dynamic_formsets.apps.DynamicFormsetsConfig'` to INSTALLED_APPS?

**Comment by iserranoe** [comment]
It doesn't work for me either

**Comment by thestick613** [comment]
Yes, this still doesn't work.

**Comment by nesdis** [comment]
Some files were missing in the packaging. I have now fixed this. It must work now!

**Comment by thestick613** [comment]
Hello, this still doesn't work:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.formset.min.js, line 0)
[Error] TypeError: undefined is not a function (near '...$...')
	Global Code (add:40)
[Error] TypeError: undefined is not a function (near '...$...')
	Global Code (add:49)
[Error] TypeError: undefined is not a function (near '...$...')
	Global Code (add:58)

**Comment by thestick613** [comment]
Just try to create a small demo app, and check it out..

**Comment by iserranoe** [comment]
I couldn't make it work either.

**Comment by nesdis** [comment]
My Bad, But version djongo-1.2.36 should fix this now

**Comment by iserranoe** [comment]
Yeees! It's working now!! Thank you so much @nesdis
