### ISSUE TITLE
'Identifier' object has no attribute 'get_identifiers' in sql2mongo.py

### ISSUE THREAD

**Issue by stuboo** [nesdis/djongo#53]
#### One line description of the issue
'Identifier' object has no attribute 'get_identifiers'

#### Python script
in `fbn/models.py`
```python
from djongo import models

class Institution(models.Model):
    institution_name = models.CharField("Institution Name", max_length=140)
    def __str__(self):
        return self.institution_name
```
in `fbn/admin.py`
```python
from django.contrib import admin

from .models import Institution
admin.site.register(Institution)
```

#### Traceback
```
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/admin/fbn/institution/add/

Django Version: 2.0.1
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'fbn.apps.FbnConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  574.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in add_view
  1553.         return self.changeform_view(request, None, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  62.             return bound_func(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  58.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1450.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1490.                 self.save_model(request, new_object, form, not add)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in save_model
  1026.         obj.save()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save
  729.                        force_update=force_update, update_fields=update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  759.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  842.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _do_insert
  880.                                using=using, raw=raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/query.py" in _insert
  1125.         return query.get_compiler(using=using).execute_sql(return_id)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1281.                 cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/cursor.py" in execute
  44.         self.result = Result(self.client_conn, self.db_conn, sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  825.         self.parse()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  875.                 return handler(self, statement)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in _insert
  988.         self._query = InsertQuery(self, self.db, sm, self._params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  730.         super().__init__(*args)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  124.         self.parse()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  763.         for aid in nexttok[1].get_identifiers():

Exception Type: AttributeError at /admin/fbn/institution/add/
Exception Value: 'Identifier' object has no attribute 'get_identifiers'
```

**Comment by nesdis** [comment]
Do you mind updating to the latest version and reproducing your error.

**Comment by stuboo** [comment]
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/fbn/institution/add/

Django Version: 2.0.1
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'fbn.apps.FbnConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  574.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in add_view
  1553.         return self.changeform_view(request, None, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  62.             return bound_func(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  58.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1450.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1490.                 self.save_model(request, new_object, form, not add)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in save_model
  1026.         obj.save()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save
  729.                        force_update=force_update, update_fields=update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  759.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  842.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _do_insert
  880.                                using=using, raw=raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/query.py" in _insert
  1125.         return query.get_compiler(using=using).execute_sql(return_id)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1281.                 cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/cursor.py" in execute
  44.         self.result = Result(self.client_conn, self.db_conn, sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  825.         self.parse()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  875.             try:

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in _insert
  988.             raise SQLDecodeError('statement:{}'.format(sm))

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  730.         super().__init__(*args)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  124.         self.parse()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  763.         for aid in nexttok[1].get_identifiers():

Exception Type: AttributeError at /admin/fbn/institution/add/
Exception Value: 'Identifier' object has no attribute 'get_identifiers'

```

**Comment by nesdis** [comment]
can you please tell me how you updated to the latest version? 

`pip install -U djongo`

The traceback you print is not as expected and is missing the SQL that caused the failure

**Comment by stuboo** [comment]
`pip install djongo --upgrade `
  

  
  

  
  
>

**Comment by nesdis** [comment]
If you run:

`pip freeze | grep 'djongo'`

do you get:

`djongo==1.2.15`

**Comment by nesdis** [comment]
Hello @stuboo The issue has been fixed. It was a silly miss on my part. For the moment please do:

`pip install git+https://github.com/nesdis/djongo`

and get unblocked! I will release a new version to pypi sometime soon

**Comment by stuboo** [comment]
@nesdis This is odd.  I upgraded again (to 1.2.16) and am still getting the same error.  I'm going to start with a fresh database and try again.  Thanks for you work on this so far. Stay tuned.

**Comment by stuboo** [comment]
Unfortunately, same error.

```python
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/admin/fbn/institution/add/

Django Version: 2.0.1
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'fbn.apps.FbnConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  574.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in add_view
  1553.         return self.changeform_view(request, None, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  62.             return bound_func(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  58.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1450.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1490.                 self.save_model(request, new_object, form, not add)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/contrib/admin/options.py" in save_model
  1026.         obj.save()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save
  729.                        force_update=force_update, update_fields=update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in save_base
  759.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _save_table
  842.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/base.py" in _do_insert
  880.                                using=using, raw=raw)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/query.py" in _insert
  1125.         return query.get_compiler(using=using).execute_sql(return_id)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/models/sql/compiler.py" in execute_sql
  1281.                 cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  100.             return super().execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in execute
  68.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  77.         return executor(sql, params, many, context)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/django/db/backends/utils.py" in _execute
  85.                 return self.cursor.execute(sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/cursor.py" in execute
  44.         self.result = Result(self.client_conn, self.db_conn, sql, params)

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  825.         self._params_index_count = -1

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  875.             handler = self.FUNC_MAP[sm_type]

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in _insert
  988.             logger.debug('Not supported {}'.format(sm))

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  730.     def __init__(self, result_ref: 'Result', *args):

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in __init__
  124.         self.parse()

File "/Users/jrs/.virtualenvs/mysite/lib/python3.6/site-packages/djongo/sql2mongo.py" in parse
  763.         nextid, nexttok = sm.token_next(nextid)

Exception Type: AttributeError at /admin/fbn/institution/add/
Exception Value: 'Identifier' object has no attribute 'get_identifiers'

```

**Comment by stuboo** [comment]
I looked at your previous edits and saw that the issue was with adding a single field to a collection. I added another field to my `fbn/models.py` and the insert went through without any issues.

```python
from djongo import models

class Institution(models.Model):
    institution_name = models.CharField("Institution Name", max_length=140)
    institution_city = models.CharField("Institution City", max_length=140)
    def __str__(self):
        return self.institution_name
```

**Comment by nesdis** [comment]
The issue has been fixed. You can clone the latest version from git. Regarding the traceback I feel the last part of it is missing. 

Typically i get more prints at the bottom. That however seems to be missing here. The traceback is what is printed in the console

**Comment by nesdis** [comment]
I hope your issue is resolved
